package testscript

import (
	"os"
	"strings"
	"testing"
	"time"
)

// A script with no atr-spec-sha256 line is hand-written. The store has always
// said so in its comments; nothing could ask it, so the caller that decides
// whether to compile asked Fresh instead and read "not fresh" as "the spec
// changed".

func TestHandWrittenIsTheMissingSpecHashAndNothingElse(t *testing.T) {
	const body = "atr.step(1, \"x\", () => { expect(1).toBe(1); });\n"
	hash := specHeader + SpecHash(spec) + "\n"

	tests := []struct {
		name        string
		source      string
		handWritten bool
		fresh       bool
	}{
		{"a bare script", body, true, false},
		{"a script with its own comments", "// Mine. Do not regenerate.\n" + body, true, false},
		{"a compiled script", "// Generated by ATR\n" + hash + body, false, true},
		{"a compiled script for another spec", "// Generated by ATR\n" + specHeader + SpecHash("something else") + "\n" + body, false, false},
		{"a draft", "// Generated by ATR\n" + hash + unverifiedHeader + "\n" + body, false, false},
		// The documented gesture, applied to a draft: the hash goes, the note
		// about never having run stays behind. Still hand-written.
		{"a draft with the hash line removed", "// Generated by ATR\n" + unverifiedHeader + "\n" + body, true, false},
		{"a compiled script that kept only its library hash", "// Generated by ATR\n" + libHeader + SpecHash("lib") + "\n" + body, true, false},
		{"a script that mentions the marker in passing", "// I took out the atr-spec-sha256 line on purpose.\n" + body, true, false},

		// The hash line is still in the file, only no longer where the header
		// is read from. That is a compiled script that cannot be vouched for,
		// not one somebody has claimed: calling it hand-written would replay
		// it for ever, whatever became of the spec. It is compiled again, as
		// it always was.
		{"a licence comment above the header", "/* Copyright someone */\n// Generated by ATR\n" + hash + body, false, false},
		{"'use strict' above the header", "'use strict';\n// Generated by ATR\n" + hash + body, false, false},
		{"a byte-order mark before the header", "\ufeff// Generated by ATR\n" + hash + body, false, false},
		{"a byte-order mark on the hash line itself", "\ufeff" + hash + body, false, false},
		{"a hash line below the first statement", body + hash, false, false},
		{"an indented hash line", "// Generated by ATR\n  " + hash + body, false, true},

		// Nothing to replay, and nobody's.
		{"an empty file", "", false, false},
		{"a file of blank lines", "\n\n  \n", false, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			specPath := writeSpec(t, spec)
			if err := os.WriteFile(ScriptPath(specPath), []byte(tt.source), 0o644); err != nil {
				t.Fatal(err)
			}

			stored, err := Load(specPath)
			if err != nil {
				t.Fatal(err)
			}
			if got := stored.HandWritten(); got != tt.handWritten {
				t.Errorf("HandWritten() = %v, want %v", got, tt.handWritten)
			}
			if got := stored.Fresh(spec); got != tt.fresh {
				t.Errorf("Fresh() = %v, want %v", got, tt.fresh)
			}
			// The two are never both true: a script ATR compiled from this
			// spec is by definition not one a person has taken over.
			if stored.HandWritten() && stored.Fresh(spec) {
				t.Error("a script is both hand-written and fresh")
			}
		})
	}
}

// What ATR writes is never hand-written, at any point in its life.
func TestNothingATRWritesIsHandWritten(t *testing.T) {
	specPath := writeSpec(t, spec)
	lib := writeLibrary(t, specPath, "function signIn() {}\n")

	check := func(stage string) {
		t.Helper()
		stored, err := Load(specPath)
		if err != nil {
			t.Fatal(err)
		}
		if stored.HandWritten() {
			t.Errorf("after %s the script reads as hand-written:\n%s", stage, stored.Source)
		}
	}

	if _, err := SaveDraft(specPath, spec, "atr.step(1, 'x', () => {});", lib.Hash()); err != nil {
		t.Fatal(err)
	}
	check("SaveDraft")

	if err := Stamp(specPath, lib.Hash()); err != nil {
		t.Fatal(err)
	}
	check("Stamp")

	if err := Stamp(specPath, ""); err != nil {
		t.Fatal(err)
	}
	check("Stamp with the library removed")

	if _, err := Save(specPath, spec, "atr.step(1, 'y', () => {});", ""); err != nil {
		t.Fatal(err)
	}
	check("Save")
}

// Stamp does not write to a hand-written script at all. It never added a
// header to one, but it did replace the file with a copy of itself — and
// "left alone" means the file, not merely its contents.
func TestStampDoesNotWriteToAHandWrittenScript(t *testing.T) {
	longAgo := time.Date(2001, time.January, 1, 0, 0, 0, 0, time.UTC)

	tests := []struct {
		name   string
		source string
	}{
		{"plain", "// mine, thanks\natr.step(1, 'x', () => {});\n"},
		// Stamp's other job is to clear this note. Not here: the file is not
		// ATR's to edit, note included.
		{"still carrying an unverified note", "// mine now\n" + unverifiedHeader + "\natr.step(1, 'x', () => {});\n"},
		{"carrying a library hash of its own", "// mine\n" + libHeader + "0000\natr.step(1, 'x', () => {});\n"},
	}

	for _, tt := range tests {
		for _, withLibrary := range []bool{true, false} {
			name := tt.name + ", no library"
			if withLibrary {
				name = tt.name + ", library beside it"
			}
			t.Run(name, func(t *testing.T) {
				specPath := writeSpec(t, spec)
				libHash := ""
				if withLibrary {
					libHash = writeLibrary(t, specPath, "function signIn() {}\n").Hash()
				}

				path := ScriptPath(specPath)
				if err := os.WriteFile(path, []byte(tt.source), 0o755); err != nil {
					t.Fatal(err)
				}
				// Backdated, so that any write shows however fast it follows.
				if err := os.Chtimes(path, longAgo, longAgo); err != nil {
					t.Fatal(err)
				}
				// What the file's mode is here, rather than what was asked for:
				// Windows has no executable bit to keep.
				created, err := os.Stat(path)
				if err != nil {
					t.Fatal(err)
				}
				modeBefore := created.Mode().Perm()

				if err := Stamp(specPath, libHash); err != nil {
					t.Fatalf("Stamp: %v", err)
				}

				after, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				if string(after) != tt.source {
					t.Errorf("a hand-written script was rewritten:\n%s", after)
				}
				info, err := os.Stat(path)
				if err != nil {
					t.Fatal(err)
				}
				if !info.ModTime().Equal(longAgo) {
					t.Errorf("the file was written to: its modification time moved to %v", info.ModTime())
				}
				// Replacing the file through a temporary one also resets its
				// mode, which is how an executable script would lose its bit.
				if info.Mode().Perm() != modeBefore {
					t.Errorf("the file's mode changed from %v to %v", modeBefore, info.Mode().Perm())
				}
				if strings.Contains(string(after), specHeader) {
					t.Error("a spec hash appeared in a hand-written script")
				}
			})
		}
	}
}
