package testscript

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The compiled script lives next to the spec it came from: login.test.txt
// compiles to login.test.js. It is meant to be committed. A generated script
// is the part of the suite that actually runs, so it needs to be reviewable
// in a diff and reproducible on a machine that has never run the compiler —
// hiding it in a cache directory would make a test suite whose behaviour
// depends on who ran it last.

// specHeader is the marker line carrying the hash of the spec a script was
// compiled from. Kept on line 2 so it survives a shebang and stays visible in
// a diff.
const specHeader = "// atr-spec-sha256: "

// unverifiedHeader marks a script that has been compiled but has not yet
// completed a run.
//
// A compile used to be trusted the moment the model stopped talking: the
// script was written and stamped before it had ever executed, so a script that
// did not run was reported as fresh and replayed on every later run instead of
// being recompiled.
//
// This is a marker of its own rather than the absence of a hash, because the
// absence of a hash already means something else — it is how a human marks a
// script as hand-written and off-limits to the compiler. See HandWritten.
const unverifiedHeader = "// atr-unverified: compiled but not yet run"

// libHeader records the hash of the shared library a script was compiled
// against.
//
// Kept separate from the spec hash rather than folded into it. A single merged
// hash cannot say which of the two moved, and the error message has to name
// it: "the spec changed" and "the library changed" call for different actions
// and different amounts of money.
const libHeader = "// atr-lib-sha256: "

// generatedHeader is prepended to every compiled script.
const generatedHeader = `// Generated by ATR from %s — edit the spec, not this file.
%s%s
// Re-compile with: atr run --behavior %s --recompile
`

// ScriptPath returns the compiled script path for a spec file.
func ScriptPath(specPath string) string {
	ext := filepath.Ext(specPath)
	base := strings.TrimSuffix(specPath, ext)
	// login.test.txt -> login.test.js
	return base + ".js"
}

// SpecHash is the content hash recorded in a compiled script.
func SpecHash(spec string) string {
	sum := sha256.Sum256([]byte(normalize(spec)))
	return hex.EncodeToString(sum[:])
}

// normalize makes the hash insensitive to whitespace-only edits, so
// reflowing a spec does not force a recompile that would cost tokens and
// change nothing.
func normalize(spec string) string {
	lines := strings.Split(spec, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		line = strings.TrimRight(line, " \t\r")
		if line == "" {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// Stored is a compiled script read from disk.
type Stored struct {
	// Path is where the script lives.
	Path string
	// Source is the JavaScript.
	Source string
	// SpecHash is the hash the script was compiled against, empty if the
	// script carries no header.
	SpecHash string
	// Unverified is true for a script that has been compiled but has not yet
	// completed a run, so it is not yet trusted.
	Unverified bool
	// LibHash is the hash of the shared library the script was compiled
	// against, empty when there was none.
	LibHash string
}

// LibraryChanged reports whether the shared library has moved since this
// script was compiled.
//
// Deliberately NOT part of Fresh. A library change does not mean the script is
// wrong; it means the script is unproven against the current library, which is
// a replay, not a recompile. Folding it into freshness would make a one-line
// fix to login() cost a model compile per spec in the directory, rewrite every
// committed script as a whole-file diff, and turn CI red until somebody re-ran
// them all locally — for a change whose whole purpose was to fix them.
func (s *Stored) LibraryChanged(libHash string) bool {
	return s.LibHash != libHash
}

// Fresh reports whether the script was compiled from this exact spec.
//
// A script with no header is never fresh, and that is the whole of what this
// says about it: there is nothing to hold the spec against. It is not thereby
// stale. Not-fresh was once read as "the spec changed", which sent a
// hand-written script to the compiler to be overwritten — so a caller deciding
// what to do with a script asks HandWritten first.
func (s *Stored) Fresh(spec string) bool {
	return s.SpecHash != "" && !s.Unverified && s.SpecHash == SpecHash(spec)
}

// HandWritten reports whether a person has taken this script over.
//
// The marker is the missing spec hash line and nothing else. Every script ATR
// writes carries one, so its absence can only be someone's doing, and what it
// asks for is to be left alone: replayed as it stands, and never compiled
// over, repaired, stamped or hoisted.
//
// Nothing else in the header is consulted. A script that kept its
// atr-unverified note but lost its hash is hand-written too — reading that
// note as "compile again" would overwrite the file by the one route its owner
// has just closed.
//
// Missing means missing from the whole file, which is a narrower thing than
// SpecHash being empty. SpecHash is read from the comment block at the top, so
// a licence comment, a 'use strict' or a byte-order mark above that block
// leaves it empty while the line is still there. That is a compiled script ATR
// can no longer vouch for, not one somebody has claimed, and treating it as
// claimed would replay it for ever: a later spec edit would never take effect
// and CI would stay green. It stays what it was before — not fresh, so
// compiled again. An empty file is nobody's script either.
func (s *Stored) HandWritten() bool {
	return strings.TrimSpace(s.Source) != "" && !hasSpecHashLine(s.Source)
}

// hasSpecHashLine reports whether any line of a script is a spec hash line,
// wherever in the file it sits.
func hasSpecHashLine(source string) bool {
	marker := strings.TrimSpace(specHeader)
	for _, line := range strings.Split(source, "\n") {
		line = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "\ufeff"))
		if strings.HasPrefix(line, marker) {
			return true
		}
	}
	return false
}

// Load reads the compiled script for a spec, if one exists.
// A missing script is not an error — it just means nothing has been compiled
// yet.
func Load(specPath string) (*Stored, error) {
	path := ScriptPath(specPath)

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading compiled script %s: %w", path, err)
	}

	return &Stored{
		Path:       path,
		Source:     string(data),
		SpecHash:   parseHeader(string(data), specHeader),
		LibHash:    parseHeader(string(data), libHeader),
		Unverified: strings.Contains(string(data), unverifiedHeader),
	}, nil
}

// Save writes a compiled script, stamping it with the spec's hash and the
// hash of the library it was compiled against.
func Save(specPath, spec, source, libHash string) (string, error) {
	return writeScript(specPath, spec, source, libHash, false)
}

// SaveDraft writes a compiled script that has not run yet.
//
// It carries the spec hash like any other, plus a marker saying it is
// unproven, so Fresh will not hand it to a later run. Written before the
// verification replay rather than held in memory, so an interrupted run leaves
// the expensive part of the work on disk to look at.
func SaveDraft(specPath, spec, source, libHash string) (string, error) {
	return writeScript(specPath, spec, source, libHash, true)
}

// Stamp marks a script as having run against this library, so later runs may
// replay it.
//
// Two things, because they are the same event: the script is no longer
// unproven, and the library it actually ran against is the one recorded. A
// restamp is what makes a library edit cost nothing — the run replays, passes,
// and the header catches up — and without it the same edit would report stale
// for ever.
func Stamp(specPath, libHash string) error {
	path := ScriptPath(specPath)

	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading compiled script %s: %w", path, err)
	}

	body := string(data)

	// A hand-written script is not stamped, and not written to at all. It
	// used to be rewritten with the same bytes — no header was added, but the
	// file was replaced, which is still ATR's hand in a file it had promised
	// to leave alone, and would have dropped an atr-unverified note with it.
	if !hasSpecHashLine(body) {
		return nil
	}

	if !strings.Contains(body, unverifiedHeader) &&
		parseHeader(body, libHeader) == libHash {
		return nil
	}

	var kept []string
	stamped := false
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == unverifiedHeader {
			continue
		}
		if strings.HasPrefix(trimmed, strings.TrimSpace(libHeader)) {
			if libHash == "" {
				// The library was removed; so is its header.
				stamped = true
				continue
			}
			kept = append(kept, libHeader+libHash)
			stamped = true
			continue
		}
		kept = append(kept, line)
	}

	// A script compiled before the library existed has no header to rewrite,
	// so it gets one — provided its own header is where a header belongs. (A
	// hand-written script never reaches here.)
	if !stamped && libHash != "" && parseHeader(body, specHeader) != "" {
		kept = insertAfterSpecHeader(kept, libHeader+libHash)
	}

	return writeFileAtomic(path, strings.Join(kept, "\n"))
}

// insertAfterSpecHeader puts a header line directly below the spec hash, where
// the rest of the block lives. Callers check that a spec header exists first.
func insertAfterSpecHeader(lines []string, header string) []string {
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), strings.TrimSpace(specHeader)) {
			out := make([]string, 0, len(lines)+1)
			out = append(out, lines[:i+1]...)
			out = append(out, header)
			return append(out, lines[i+1:]...)
		}
	}
	return lines
}

func writeScript(specPath, spec, source, libHash string, draft bool) (string, error) {
	path := ScriptPath(specPath)

	// Strip any header the model reproduced, so stamping cannot double up.
	source = stripGeneratedHeader(source)

	header := fmt.Sprintf(generatedHeader,
		filepath.Base(specPath), specHeader, SpecHash(spec), specPath)
	if libHash != "" {
		header += libHeader + libHash + "\n"
	}
	if draft {
		header += unverifiedHeader + "\n"
	}
	body := header + "\n" + strings.TrimLeft(source, "\n")

	if err := writeFileAtomic(path, body); err != nil {
		return "", fmt.Errorf("writing compiled script %s: %w", path, err)
	}
	return path, nil
}

// writeFileAtomic writes through a temporary file and renames it into place.
//
// A compiled script is committed source. A crash or a full disk partway
// through a plain write leaves a truncated file in the working tree, which is
// both a broken test and a confusing diff.
func writeFileAtomic(path, body string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		// Harmless when the rename already moved it away.
		_ = os.Remove(tmpName)
	}()

	if _, err := tmp.WriteString(body); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

// parseHeader pulls one recorded header value out of a script.
func parseHeader(source, header string) string {
	for _, line := range strings.Split(source, "\n") {
		line = strings.TrimSpace(line)
		if rest, ok := strings.CutPrefix(line, header); ok {
			return strings.TrimSpace(rest)
		}
		// The header is at the top; stop once real code starts.
		if line != "" && !strings.HasPrefix(line, "//") {
			return ""
		}
	}
	return ""
}

// stripGeneratedHeader removes a previously written header block so re-saving
// does not accumulate them.
func stripGeneratedHeader(source string) string {
	lines := strings.Split(source, "\n")
	i := 0
	for i < len(lines) {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			i++
			continue
		}
		break
	}
	// Only strip if what we skipped actually looks like our header.
	head := strings.Join(lines[:i], "\n")
	if strings.Contains(head, "Generated by ATR") || strings.Contains(head, specHeader) {
		return strings.Join(lines[i:], "\n")
	}
	return source
}
