package testscript

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const spec = "Test: Sign in\n\nSteps:\n1. Click sign in\n"

func TestScriptPathSitsNextToTheSpec(t *testing.T) {
	got := ScriptPath("/tests/login.test.txt")
	want := "/tests/login.test.js"
	if got != want {
		t.Errorf("ScriptPath = %q, want %q", got, want)
	}
}

func TestLoadMissingScriptIsNotAnError(t *testing.T) {
	stored, err := Load(filepath.Join(t.TempDir(), "nothing.test.txt"))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if stored != nil {
		t.Error("a missing script should read as nil, not an error")
	}
}

func TestSaveAndLoadRoundTrip(t *testing.T) {
	specPath := filepath.Join(t.TempDir(), "login.test.txt")
	src := `atr.step(1, "Click", () => { atr.click("#go"); });`

	path, err := Save(specPath, spec, src, "")
	if err != nil {
		t.Fatalf("Save: %v", err)
	}

	stored, err := Load(specPath)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if stored == nil {
		t.Fatal("expected the saved script back")
	}
	if stored.Path != path {
		t.Errorf("Path = %q, want %q", stored.Path, path)
	}
	if !strings.Contains(stored.Source, `atr.click("#go")`) {
		t.Error("the script body did not survive the round trip")
	}
	if !stored.Fresh(spec) {
		t.Error("a just-saved script should be fresh for its own spec")
	}
}

// A changed spec must invalidate the script, or the suite keeps testing
// requirements that no longer exist.
func TestEditedSpecIsNotFresh(t *testing.T) {
	specPath := filepath.Join(t.TempDir(), "login.test.txt")
	if _, err := Save(specPath, spec, "atr.step(1, \"x\", () => {});", ""); err != nil {
		t.Fatal(err)
	}

	stored, err := Load(specPath)
	if err != nil {
		t.Fatal(err)
	}
	if stored.Fresh(spec + "2. And another thing\n") {
		t.Error("a script must not be fresh for a spec it was not compiled from")
	}
}

// Reflowing a spec costs a recompile if the hash is naive, and recompiles
// cost money.
func TestWhitespaceOnlyEditsStayFresh(t *testing.T) {
	specPath := filepath.Join(t.TempDir(), "login.test.txt")
	if _, err := Save(specPath, spec, "atr.step(1, \"x\", () => {});", ""); err != nil {
		t.Fatal(err)
	}

	stored, err := Load(specPath)
	if err != nil {
		t.Fatal(err)
	}

	reflowed := strings.ReplaceAll(spec, "\n", "\n\n") + "  \t\n"
	if !stored.Fresh(reflowed) {
		t.Error("whitespace-only edits should not invalidate a compiled script")
	}
}

// A hand-written script has no provenance, so it can never be assumed to
// match the spec.
func TestScriptWithoutHeaderIsNeverFresh(t *testing.T) {
	dir := t.TempDir()
	specPath := filepath.Join(dir, "login.test.txt")
	if err := os.WriteFile(ScriptPath(specPath), []byte("atr.step(1, \"x\", () => {});"), 0o644); err != nil {
		t.Fatal(err)
	}

	stored, err := Load(specPath)
	if err != nil {
		t.Fatal(err)
	}
	if stored.Fresh(spec) {
		t.Error("a script with no spec header must not be treated as fresh")
	}
}

// Re-saving must not stack headers on top of each other.
func TestResavingDoesNotAccumulateHeaders(t *testing.T) {
	specPath := filepath.Join(t.TempDir(), "login.test.txt")
	src := `atr.step(1, "Click", () => { atr.click("#go"); });`

	if _, err := Save(specPath, spec, src, ""); err != nil {
		t.Fatal(err)
	}
	first, err := Load(specPath)
	if err != nil {
		t.Fatal(err)
	}

	// Feed the stored form — header and all — straight back in, which is what
	// happens when a model echoes the file it was shown.
	if _, err := Save(specPath, spec, first.Source, ""); err != nil {
		t.Fatal(err)
	}
	second, err := Load(specPath)
	if err != nil {
		t.Fatal(err)
	}

	if n := strings.Count(second.Source, "Generated by ATR"); n != 1 {
		t.Errorf("header appears %d times, want 1", n)
	}
	if n := strings.Count(second.Source, specHeader); n != 1 {
		t.Errorf("spec hash appears %d times, want 1", n)
	}
	if !second.Fresh(spec) {
		t.Error("re-saved script should still be fresh")
	}
}
