package testscript

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The compiled script lives next to the spec it came from: login.test.txt
// compiles to login.test.js. It is meant to be committed. A generated script
// is the part of the suite that actually runs, so it needs to be reviewable
// in a diff and reproducible on a machine that has never run the compiler —
// hiding it in a cache directory would make a test suite whose behaviour
// depends on who ran it last.

// specHeader is the marker line carrying the hash of the spec a script was
// compiled from. Kept on line 2 so it survives a shebang and stays visible in
// a diff.
const specHeader = "// atr-spec-sha256: "

// unverifiedHeader marks a script that has been compiled but has not yet
// completed a run.
//
// A compile used to be trusted the moment the model stopped talking: the
// script was written and stamped before it had ever executed, so a script that
// did not run was reported as fresh and replayed on every later run instead of
// being recompiled.
//
// This is a marker of its own rather than the absence of a hash, because the
// absence of a hash already means something else — it is how a human marks a
// script as hand-written and off-limits to the compiler.
const unverifiedHeader = "// atr-unverified: compiled but not yet run"

// generatedHeader is prepended to every compiled script.
const generatedHeader = `// Generated by ATR from %s — edit the spec, not this file.
%s%s
// Re-compile with: atr run --behavior %s --recompile
`

// ScriptPath returns the compiled script path for a spec file.
func ScriptPath(specPath string) string {
	ext := filepath.Ext(specPath)
	base := strings.TrimSuffix(specPath, ext)
	// login.test.txt -> login.test.js
	return base + ".js"
}

// SpecHash is the content hash recorded in a compiled script.
func SpecHash(spec string) string {
	sum := sha256.Sum256([]byte(normalize(spec)))
	return hex.EncodeToString(sum[:])
}

// normalize makes the hash insensitive to whitespace-only edits, so
// reflowing a spec does not force a recompile that would cost tokens and
// change nothing.
func normalize(spec string) string {
	lines := strings.Split(spec, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		line = strings.TrimRight(line, " \t\r")
		if line == "" {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// Stored is a compiled script read from disk.
type Stored struct {
	// Path is where the script lives.
	Path string
	// Source is the JavaScript.
	Source string
	// SpecHash is the hash the script was compiled against, empty if the
	// script carries no header.
	SpecHash string
	// Unverified is true for a script that has been compiled but has not yet
	// completed a run, so it is not yet trusted.
	Unverified bool
}

// Fresh reports whether the script was compiled from this exact spec.
//
// A script with no header is never fresh: it was hand-written or produced by
// an older version, and the safe assumption is that it may not match.
func (s *Stored) Fresh(spec string) bool {
	return s.SpecHash != "" && !s.Unverified && s.SpecHash == SpecHash(spec)
}

// Load reads the compiled script for a spec, if one exists.
// A missing script is not an error — it just means nothing has been compiled
// yet.
func Load(specPath string) (*Stored, error) {
	path := ScriptPath(specPath)

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading compiled script %s: %w", path, err)
	}

	return &Stored{
		Path:       path,
		Source:     string(data),
		SpecHash:   parseSpecHash(string(data)),
		Unverified: strings.Contains(string(data), unverifiedHeader),
	}, nil
}

// Save writes a compiled script, stamping it with the spec's hash.
func Save(specPath, spec, source string) (string, error) {
	return writeScript(specPath, spec, source, false)
}

// SaveDraft writes a compiled script that has not run yet.
//
// It carries the spec hash like any other, plus a marker saying it is
// unproven, so Fresh will not hand it to a later run. Written before the
// verification replay rather than held in memory, so an interrupted run leaves
// the expensive part of the work on disk to look at.
func SaveDraft(specPath, spec, source string) (string, error) {
	return writeScript(specPath, spec, source, true)
}

// Stamp marks a script as having run, so later runs may replay it.
func Stamp(specPath string) error {
	path := ScriptPath(specPath)

	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading compiled script %s: %w", path, err)
	}

	body := string(data)
	if !strings.Contains(body, unverifiedHeader) {
		return nil
	}

	var kept []string
	for _, line := range strings.Split(body, "\n") {
		if strings.TrimSpace(line) == unverifiedHeader {
			continue
		}
		kept = append(kept, line)
	}
	return writeFileAtomic(path, strings.Join(kept, "\n"))
}

func writeScript(specPath, spec, source string, draft bool) (string, error) {
	path := ScriptPath(specPath)

	// Strip any header the model reproduced, so stamping cannot double up.
	source = stripGeneratedHeader(source)

	header := fmt.Sprintf(generatedHeader,
		filepath.Base(specPath), specHeader, SpecHash(spec), specPath)
	if draft {
		header += unverifiedHeader + "\n"
	}
	body := header + "\n" + strings.TrimLeft(source, "\n")

	if err := writeFileAtomic(path, body); err != nil {
		return "", fmt.Errorf("writing compiled script %s: %w", path, err)
	}
	return path, nil
}

// writeFileAtomic writes through a temporary file and renames it into place.
//
// A compiled script is committed source. A crash or a full disk partway
// through a plain write leaves a truncated file in the working tree, which is
// both a broken test and a confusing diff.
func writeFileAtomic(path, body string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		// Harmless when the rename already moved it away.
		_ = os.Remove(tmpName)
	}()

	if _, err := tmp.WriteString(body); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

// parseSpecHash pulls the recorded spec hash out of a script.
func parseSpecHash(source string) string {
	for _, line := range strings.Split(source, "\n") {
		line = strings.TrimSpace(line)
		if rest, ok := strings.CutPrefix(line, specHeader); ok {
			return strings.TrimSpace(rest)
		}
		// The header is at the top; stop once real code starts.
		if line != "" && !strings.HasPrefix(line, "//") {
			return ""
		}
	}
	return ""
}

// stripGeneratedHeader removes a previously written header block so re-saving
// does not accumulate them.
func stripGeneratedHeader(source string) string {
	lines := strings.Split(source, "\n")
	i := 0
	for i < len(lines) {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			i++
			continue
		}
		break
	}
	// Only strip if what we skipped actually looks like our header.
	head := strings.Join(lines[:i], "\n")
	if strings.Contains(head, "Generated by ATR") || strings.Contains(head, specHeader) {
		return strings.Join(lines[i:], "\n")
	}
	return source
}
