// Generated by ATR from browse-by-tag.test.txt — edit the spec, not this file.
// atr-spec-sha256: 026c4d0d62e43c853fa4db591fcfdc393b628b21bbff0505975ff542e22d2aa3
// Re-compile with: atr run --behavior tests/browse-by-tag.test.txt --recompile
// atr-lib-sha256: 949f5c004d8932076e872d241d27f30ea263ed543cda4cde29d335dd5d35c121

// Test: A reader can narrow the blog to one tag

const TAGS_PATH = values.get("tags_path");
const TAG_SLUG = "rest";
const MIN_POSTS = values.int("min_tagged_posts");

const POST_LINKS = 'div[role="main"] ul li a';
const OLDER_LINK = 'a.pagination-item:has-text("Older")';

atr.setup("Confirm the front page is published and paginated", () => {
  openHome();
  // Baseline for the final comparison: the front page carries an "Older" link.
  atr.expectExists(OLDER_LINK, { timeout: 10000 });
});

atr.step(1, "Open the tags page at /tags/", () => {
  atr.navigate(TAGS_PATH);
  atr.expectExists('a[href$="/tags/' + TAG_SLUG + '"]', { timeout: 10000 });
});

atr.step(2, 'Follow the link for the "rest" tag', () => {
  atr.click('a[href$="/tags/' + TAG_SLUG + '"]');
  atr.waitFor(POST_LINKS, { timeout: 10000, visible: true });
});

atr.step(3, "Confirm the reader is looking at that tag's posts", () => {
  // The URL is the rest tag's page.
  expect(atr.url()).toContain("/tags/" + TAG_SLUG);

  // The page names the tag it is showing.
  atr.expectText('div[role="main"] p', "Tag: " + TAG_SLUG, {
    timeout: 10000,
    contains: true,
  });

  // At least one post is listed.
  const listed = atr.eval(
    'document.querySelectorAll(\'div[role="main"] ul li a\').length'
  );
  atr.log("Posts listed under tag " + TAG_SLUG + ": " + listed);
  expect(Number(listed)).toBeGreaterThan(MIN_POSTS - 1);

  // The listing is narrower than the front page: no "Older" pagination link.
  atr.expectMissing(OLDER_LINK, { timeout: 5000 });
});