// Generated by ATR from browse-by-tag.test.txt — edit the spec, not this file.
// atr-spec-sha256: 4f0ccd6a12a502ea08855ef43e9370f3bdd2d9389543d47920a6b85a4cb2813a
// atr-lib-sha256: c7aba3504deddcbdc4736f56b93a4cfe490c809e20adc657e483c45f4980d75e
// Re-compile with: atr run --behavior tests/browse-by-tag.test.txt --recompile

const TAG = values.get("tag_name");

atr.step(1, 'Open the tags page at /tags/ and follow the link for the "rest" tag', () => {
  openTagsPage(values.get("tags_path", "/tags/"), TAG);
  openTagPage(TAG);
});

atr.step(2, "Confirm the reader is looking at that tag's posts", () => {
  // The URL is the rest tag's page
  expect(atr.url()).toContain(values.get("tag_path_fragment"));

  // The page names the tag it is showing
  atr.expectText('div[role="main"] .measure p', "Tag: " + TAG, {
    contains: true,
    timeout: 15000,
  });

  // At least one post is listed
  atr.expectExists('div[role="main"] .measure ul li a', { timeout: 15000 });
  const listed = Number(
    atr.eval('document.querySelectorAll(\'div[role="main"] .measure ul li a\').length')
  );
  atr.log("posts listed under tag " + TAG + ": " + listed);
  expect(listed).toBeGreaterThan(values.int("min_posts") - 1);

  // The listing is narrower than the front page: no "Older" pagination link here
  atr.expectMissing('a.pagination-item:has-text("Older")', { timeout: 5000 });
});
