// Generated by ATR from older-posts.test.txt — edit the spec, not this file.
// atr-spec-sha256: 56dcc951964c2189ce9b501f4853b90cd4b4c4cfb7f1b5f62cbebe4a095f3aa8
// atr-lib-sha256: c7aba3504deddcbdc4736f56b93a4cfe490c809e20adc657e483c45f4980d75e
// Re-compile with: atr run --behavior tests/older-posts.test.txt --recompile

// Reader pages back through older posts via the "Older" pagination link.

let frontPageFirstTitle = "";

atr.step(1, "Open the front page and note which post titles it lists", () => {
  atr.navigate(values.get("front_page_path", "/"));

  atr.expectExists('div[role="main"] .post-title', { timeout: 15000 });

  const titles = atr.eval(
    'JSON.stringify(Array.prototype.map.call(document.querySelectorAll(\'div[role="main"] .post-title\'), function (e) { return e.textContent.trim(); }))'
  );
  const frontTitles = JSON.parse(titles);
  atr.log("front page titles: " + frontTitles.join(" | "));

  expect(frontTitles.length).toBeGreaterThan(values.int("min_posts") - 1);

  frontPageFirstTitle = frontTitles[0];
  expect(frontPageFirstTitle.length).toBeGreaterThan(0);

  // Pagination is the only route to the archive, so the front page must offer it.
  atr.expectExists('a.pagination-item:has-text("Older")', { timeout: 15000 });
});

atr.step(2, 'Follow the "Older" link at the foot of the list', () => {
  atr.click('a.pagination-item:has-text("Older")');
  atr.waitFor('div[role="main"] .post-title', { timeout: 15000, visible: true });
});

atr.step(3, "Confirm this is a different page of posts", () => {
  // The URL is the second page of the listing
  expect(atr.url()).toContain(values.get("second_page_path"));

  const titles = atr.eval(
    'JSON.stringify(Array.prototype.map.call(document.querySelectorAll(\'div[role="main"] .post-title\'), function (e) { return e.textContent.trim(); }))'
  );
  const olderTitles = JSON.parse(titles);
  atr.log("second page titles: " + olderTitles.join(" | "));

  // Posts are still listed: the page is not empty
  expect(olderTitles.length).toBeGreaterThan(values.int("min_posts") - 1);

  // The post titles here are different from the ones on the front page
  expect(olderTitles[0]).not === undefined;
  if (olderTitles[0] === frontPageFirstTitle) {
    atr.fail(
      'The second page repeats the front page\'s first post title: "' + frontPageFirstTitle + '"'
    );
  }
  expect(olderTitles.indexOf(frontPageFirstTitle)).toBe(-1);

  // A link back towards the newer posts is now offered
  atr.expectExists('a.pagination-item:has-text("Newer")', { timeout: 15000 });
});