// Generated by ATR from older-posts.test.txt — edit the spec, not this file.
// atr-spec-sha256: 56dcc951964c2189ce9b501f4853b90cd4b4c4cfb7f1b5f62cbebe4a095f3aa8
// Re-compile with: atr run --behavior tests/older-posts.test.txt --recompile
// atr-lib-sha256: 949f5c004d8932076e872d241d27f30ea263ed543cda4cde29d335dd5d35c121

// Test: A reader can page back through older posts

let frontPageFirstTitle = "";

atr.step(1, "Open the front page and note which post titles it lists", () => {
  openHome();
  atr.expectExists("h3.post-title");
  frontPageFirstTitle = atr.text("h3.post-title").trim();
  expect(frontPageFirstTitle.length).toBeGreaterThan(0);

  const frontPageCount = atr.eval("document.querySelectorAll('h3.post-title').length");
  expect(frontPageCount).toBe(values.int("front_page_post_count"));
  atr.log("Front page first title: " + frontPageFirstTitle);
});

atr.step(2, "Follow the \"Older\" link at the foot of the list", () => {
  atr.expectExists('a:has-text("Older")');
  atr.click('a:has-text("Older")');
  atr.waitFor("h3.post-title");
});

atr.step(3, "Confirm this is a different page of posts", () => {
  // The URL is the second page of the listing
  expect(atr.url()).toContain(values.get("second_page_path"));

  // Posts are still listed: the page is not empty
  atr.expectExists("h3.post-title");
  const secondPageCount = atr.eval("document.querySelectorAll('h3.post-title').length");
  expect(secondPageCount).toBeGreaterThan(0);

  // The post titles here are different from the ones on the front page
  const secondPageFirstTitle = atr.text("h3.post-title").trim();
  expect(secondPageFirstTitle.length).toBeGreaterThan(0);
  if (secondPageFirstTitle === frontPageFirstTitle) {
    atr.fail("Second page shows the same first post title as the front page: " + secondPageFirstTitle);
  }

  // A link back towards the newer posts is now offered
  atr.expectExists('a:has-text("Newer")');
});