// Generated by ATR from read-a-post.test.txt — edit the spec, not this file.
// atr-spec-sha256: 35da1665f3d0bac9ee2cf5f2b907aa78b1506989d9be5c03b822bac5ef6a05fd
// Re-compile with: atr run --behavior tests/read-a-post.test.txt --recompile
// atr-lib-sha256: 949f5c004d8932076e872d241d27f30ea263ed543cda4cde29d335dd5d35c121

// Test: A reader can open the newest post from the front page

const HOME_PATH = values.get("home_path", "/");
const POST_PATH_FRAGMENT = values.get("post_path_fragment");
const MIN_BODY_LENGTH = values.int("min_body_length");

atr.setup("The blog is published and the front page lists at least one post", () => {
  atr.navigate(HOME_PATH);
  atr.expectExists("a.post-link", { timeout: 15000 });
});

atr.step(1, "Open the front page using openFirstPost() from the shared library, which follows the first post link", () => {
  openFirstPost();

  // The browser is no longer on the front page: the URL contains a post path.
  const url = atr.url();
  atr.log("Landed on: " + url);
  expect(url).toContain(POST_PATH_FRAGMENT);
});

atr.step(2, "Confirm the reader has landed on the post itself", () => {
  // The page shows the post's own title as a heading.
  atr.expectExists("h1", { timeout: 10000 });
  const heading = atr.text("h1").trim();
  expect(heading.length).toBeGreaterThan(0);

  // The same title text is what the page is titled after.
  expect(atr.title()).toContain(heading);

  // The post's body text is on the page, not just its summary.
  atr.expectExists(".post-content", { timeout: 10000 });
  const body = atr.text(".post-content").trim();
  expect(body.length).toBeGreaterThan(MIN_BODY_LENGTH);

  // The site header linking back to the blog home is still present.
  atr.expectExists("header.site-header a.site-title");
  const homeHref = atr.eval("document.querySelector('header.site-header a.site-title').getAttribute('href')");
  expect(homeHref).toBeTruthy();
});