// Generated by ATR from read-a-post.test.txt — edit the spec, not this file.
// atr-spec-sha256: 7456769543820566759eb055e5fdc7159854272a8c1d9f51761694cb08dd1055
// Re-compile with: atr run --behavior tests/read-a-post.test.txt --recompile
// atr-lib-sha256: c7aba3504deddcbdc4736f56b93a4cfe490c809e20adc657e483c45f4980d75e

// Reader opens the newest post from the front page and lands on the post itself.

const FRONT_PAGE_PATH = values.get("front_page_path", "/");
const POST_LINK = "a.post-link";

let firstPostTitle = "";

atr.step(1, "Open the front page and follow the link for the first post listed", () => {
  atr.navigate(FRONT_PAGE_PATH);
  atr.waitFor(POST_LINK, { timeout: 15000, visible: true });

  firstPostTitle = atr.eval(
    "document.querySelector('" + POST_LINK + " h3').textContent.trim()"
  );
  atr.log("first post listed on the front page: " + firstPostTitle);

  atr.click(POST_LINK);
  atr.waitFor(".post-content", { timeout: 15000, visible: true });
});

atr.step(2, "Confirm the reader has landed on the post itself", () => {
  // No longer on the front page: the URL is a post path
  const url = atr.url();
  atr.log("landed on: " + url);
  expect(url).toContain(values.get("post_path_fragment"));

  // The post's own title is shown as a heading, and it is the post that was clicked
  atr.expectExists("div[role=\"main\"] h1", { timeout: 15000 });
  const heading = atr.text("div[role=\"main\"] h1").trim();
  expect(heading.length).toBeGreaterThan(0);
  expect(heading).toBe(firstPostTitle);

  // The body text is on the page, not just the summary
  atr.expectExists(".post-content", { timeout: 15000 });
  const body = atr.text(".post-content").trim();
  atr.log("post body length: " + body.length);
  expect(body.length).toBeGreaterThan(values.int("min_body_length"));

  // The site header linking back to the blog home is still present
  atr.expectExists("header.site-header a.site-title", { timeout: 15000 });
  const homeHref = atr.eval(
    "document.querySelector('header.site-header a.site-title').getAttribute('href')"
  );
  atr.log("site title links to: " + homeHref);
  expect(homeHref).toContain(values.get("home_href_fragment"));
});