// Generated by ATR from tag-shows-its-own-posts.test.txt — edit the spec, not this file.
// atr-spec-sha256: d1872a22abf46c622414f4f60adb676ffca19d9cc5ede040028606f8037deaef
// atr-lib-sha256: c7aba3504deddcbdc4736f56b93a4cfe490c809e20adc657e483c45f4980d75e
// Re-compile with: atr run --behavior tests/tag-shows-its-own-posts.test.txt --recompile

const TAG = values.get("tag_name");

let tagsOffered = 0;

atr.step(1, 'Open the tags page at /tags/ and follow the link for the "linux" tag', () => {
  openTagsPage(values.get("tags_path", "/tags/"), TAG);

  // How many tags the tags page offers, read before leaving it.
  tagsOffered = Number(
    atr.eval('document.querySelectorAll(\'div[role="main"] a[href*="/tags/"]\').length')
  );
  atr.log("tags offered on the tags page: " + tagsOffered);

  openTagPage(TAG);
});

atr.step(2, "Confirm this tag's page is showing its own posts", () => {
  // The URL is the linux tag's page
  expect(atr.url()).toContain(values.get("tag_path_fragment"));

  // The page names the tag it is showing
  atr.expectText('div[role="main"] .measure p', "Tag: " + TAG, {
    contains: true,
    timeout: 15000,
  });

  // At least one post is listed
  atr.expectExists('div[role="main"] .measure ul li a', { timeout: 15000 });
  const listed = Number(
    atr.eval('document.querySelectorAll(\'div[role="main"] .measure ul li a\').length')
  );
  atr.log("posts listed under tag " + TAG + ": " + listed);
  expect(listed).toBeGreaterThan(values.int("min_posts") - 1);

  // A filtered view, not the whole archive: fewer posts here than the tags page offers tags
  expect(tagsOffered).toBeGreaterThan(listed);
});
