package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"

	"github.com/imyousuf/agentic-test-runner/internal/record"
)

// startWait is how long "start" waits for the background recorder to say it is
// running. It covers attaching to the browser and the preflight checks, both of
// which talk to Chrome.
const startWait = 20 * time.Second

// stopWait is how long "stop" waits for a recording to write its manifest.
// Stopping flushes whatever is buffered and encodes nothing, so this is
// generous rather than tight.
const stopWait = 30 * time.Second

// poll is the gap between checks while waiting for either of the above.
const poll = 200 * time.Millisecond

/*
spawnRecorder runs this same binary again, detached, and waits until it says it
is recording.

Re-running the binary is what makes "start" and "stop" a pair. A recording
holds a CDP session and a file handle for as long as it lasts, so something has
to stay alive; without this the caller would have to keep that process, which
is the "nohup ... &" every script was writing by hand and getting wrong.

The child is told --foreground, which is what it means from the child's point
of view: it is the process that holds the recording.
*/
func spawnRecorder(cmd *cobra.Command) error {
	output, _ := cmd.Flags().GetString("output")
	store, err := record.NewStore(output)
	if err != nil {
		return err
	}

	// Which recordings were already running, so the new one can be told apart.
	// Two "atr record start" calls can race, and the id is generated by the
	// child, so there is nothing to match on but the difference.
	before := map[string]bool{}
	running, err := store.Running()
	if err != nil {
		return err
	}
	for _, l := range running {
		before[l.ID] = true
	}

	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("finding this binary: %w", err)
	}

	// The child's output is worth keeping only when the child fails, and then
	// it is the whole error message.
	logf, err := os.CreateTemp("", "atr-record-*.log")
	if err != nil {
		return fmt.Errorf("making a log for the recorder: %w", err)
	}
	defer func() {
		_ = logf.Close()
		_ = os.Remove(logf.Name())
	}()

	// Copied rather than appended in place: append can write into os.Args'
	// backing array when it has spare capacity.
	argv := make([]string, 0, len(os.Args))
	argv = append(argv, os.Args[1:]...)
	argv = append(argv, "--foreground")

	child := exec.Command(exe, argv...)
	child.Stdout = logf
	child.Stderr = logf
	child.Stdin = nil
	child.SysProcAttr = detachAttr()
	if err := child.Start(); err != nil {
		return fmt.Errorf("starting the recorder: %w", err)
	}

	// Reaped here so the child never becomes a zombie of this process. It
	// outlives us either way: the wait ends when this command returns.
	gone := make(chan error, 1)
	go func() { gone <- child.Wait() }()

	quiet, _ := cmd.Flags().GetBool("quiet")

	deadline := time.Now().Add(startWait)
	for {
		if l, ok := newest(store, before); ok {
			if quiet {
				fmt.Println(l.ID)
				return nil
			}
			fmt.Println("ATR recording")
			fmt.Printf("  ID:     %s\n", l.ID)
			if l.Title != "" {
				fmt.Printf("  Title:  %s\n", l.Title)
			}
			fmt.Printf("  Output: %s\n", filepath.Join(store.Root(), l.ID))
			fmt.Printf("  PID:    %d\n", l.PID)
			fmt.Println("  Stop:   atr record stop")
			return nil
		}
		select {
		case <-gone:
			// It died before it ever recorded, so its output is the reason.
			out, _ := os.ReadFile(logf.Name())
			if reason := childReason(out); reason != "" {
				return fmt.Errorf("%s", reason)
			}
			return fmt.Errorf("the recorder stopped before it started recording")
		case <-time.After(poll):
		}
		if time.Now().After(deadline) {
			_ = child.Process.Kill()
			return fmt.Errorf("the recorder did not start within %s", startWait)
		}
	}
}

/*
childReason turns what the failed recorder printed into one error message.

The child is this same binary, so it has already written "Error: " in front of
its own failure. Passing that through unchanged gets it printed twice, because
the caller prints the same prefix again.
*/
func childReason(out []byte) string {
	text := strings.TrimSpace(string(out))
	if text == "" {
		return ""
	}
	// The last line is the failure; anything above it is progress output the
	// child managed to write first.
	lines := strings.Split(text, "\n")
	last := strings.TrimSpace(lines[len(lines)-1])
	return strings.TrimPrefix(last, "Error: ")
}

// newest returns a running recording that was not running before.
func newest(store *record.Store, before map[string]bool) (record.Live, bool) {
	running, err := store.Running()
	if err != nil {
		return record.Live{}, false
	}
	for _, l := range running {
		if !before[l.ID] {
			return l, true
		}
	}
	return record.Live{}, false
}

func newRecordStopCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "stop [id]",
		Short: "Stop a running recording",
		Long: `Stop a recording and wait until it can be played.

With no id it stops the newest running recording, which is the one "atr record
start" just began. Pass an id to stop a particular one, or --all to stop every
recording this machine is writing.

It returns once the manifest is on disk. A recording without a manifest is not
playable, so a script that stops and then reads would otherwise have to guess
how long to sleep.`,
		Args: cobra.MaximumNArgs(1),
		RunE: runRecordStop,
	}
	cmd.Flags().StringP("output", "o", "", "Recordings directory (default: ~/.atr/recordings)")
	cmd.Flags().Bool("all", false, "Stop every running recording")
	cmd.Flags().Duration("timeout", stopWait, "How long to wait for the manifest")
	return cmd
}

func runRecordStop(cmd *cobra.Command, args []string) error {
	f := cmd.Flags()
	output, _ := f.GetString("output")
	all, _ := f.GetBool("all")
	timeout, _ := f.GetDuration("timeout")

	store, err := record.NewStore(output)
	if err != nil {
		return err
	}
	running, err := store.Running()
	if err != nil {
		return err
	}
	if len(running) == 0 {
		return fmt.Errorf("nothing is recording")
	}

	targets := running[:0:0]
	switch {
	case all:
		targets = running
	case len(args) == 1:
		for _, l := range running {
			if l.ID == args[0] {
				targets = append(targets, l)
			}
		}
		if len(targets) == 0 {
			return fmt.Errorf("%s is not recording; \"atr record status\" lists what is", args[0])
		}
	default:
		// Running is newest first, so this is the one that was just started.
		targets = running[:1]
		if len(running) > 1 {
			fmt.Fprintf(cmd.ErrOrStderr(),
				"%d recordings are running. Stopping the newest; use --all for every one.\n",
				len(running))
		}
	}

	var failed error
	for _, l := range targets {
		if err := stopOne(store, l, timeout); err != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "%s: %v\n", l.ID, err)
			failed = fmt.Errorf("could not stop every recording")
			continue
		}
	}
	return failed
}

// stopOne interrupts a recorder and waits for the manifest it writes on the way
// out.
func stopOne(store *record.Store, l record.Live, timeout time.Duration) error {
	if l.PID <= 0 {
		return fmt.Errorf("the live marker has no pid, so this recording was written by an older build")
	}
	p, err := os.FindProcess(l.PID)
	if err != nil {
		return fmt.Errorf("finding process %d: %w", l.PID, err)
	}
	// Interrupt, never kill. A killed recorder leaves every frame on the disk
	// and no manifest, which is exactly the state "atr record repair" exists to
	// clean up after.
	if err := p.Signal(os.Interrupt); err != nil {
		return fmt.Errorf("interrupting process %d: %w", l.PID, err)
	}

	deadline := time.Now().Add(timeout)
	for {
		if m, err := store.Load(l.ID); err == nil {
			fmt.Printf("Stopped %s: %d frames over %s\n",
				m.ID, len(m.Frames), elapsed(m.DurationMs))
			return nil
		}
		if time.Now().After(deadline) {
			return fmt.Errorf(
				"interrupted, but no manifest after %s; run \"atr record repair %s\"", timeout, l.ID)
		}
		time.Sleep(poll)
	}
}

func newRecordStatusCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Show what is recording right now",
		Long: `List the recordings that are being written right now.

It exits 0 when something is recording and 1 when nothing is, so a script can
branch on it without reading the output.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			output, _ := cmd.Flags().GetString("output")
			store, err := record.NewStore(output)
			if err != nil {
				return err
			}
			running, err := store.Running()
			if err != nil {
				return err
			}
			if len(running) == 0 {
				fmt.Println("Nothing is recording.")
				// Exited here rather than returned as an error, because
				// "nothing is recording" is an answer and not a failure. A
				// returned error would print "Error:" in front of it and read
				// as though the query itself had gone wrong.
				os.Exit(1)
			}
			w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
			fmt.Fprintln(w, "ID\tELAPSED\tPID\tSOURCE\tTITLE")
			for _, l := range running {
				fmt.Fprintf(w, "%s\t%s\t%d\t%s\t%s\n",
					l.ID, elapsed(l.ElapsedMs()), l.PID, l.Source, l.Title)
			}
			return w.Flush()
		},
	}
	cmd.Flags().StringP("output", "o", "", "Recordings directory (default: ~/.atr/recordings)")
	return cmd
}
