package browser

import (
	"strings"
	"testing"
	"time"

	"github.com/go-rod/rod/lib/input"
)

// --- Selector generation tests ---
// These tests inject the selector generation JS and test it against fixture elements.

func TestSelectorByID(t *testing.T) {
	resetFixture(t)
	page, _ := testBrowser.CurrentPage()

	// Inject the selector generator function
	page.MustEval(`() => {
		window.__testGenSelector = ` + extractSelectorFunction() + `
	}`)

	result := page.MustEval(`() => {
		const el = document.querySelector('#test-button');
		return window.__testGenSelector(el);
	}`).Str()

	if result != "#test-button" {
		t.Errorf("expected '#test-button', got '%s'", result)
	}
}

func TestSelectorByDataTestID(t *testing.T) {
	resetFixture(t)
	page, _ := testBrowser.CurrentPage()

	page.MustEval(`() => {
		window.__testGenSelector = ` + extractSelectorFunction() + `
	}`)

	result := page.MustEval(`() => {
		const el = document.querySelector('[data-testid="testid-element"]');
		return window.__testGenSelector(el);
	}`).Str()

	if result != `[data-testid="testid-element"]` {
		t.Errorf("expected '[data-testid=\"testid-element\"]', got '%s'", result)
	}
}

func TestSelectorByAriaLabel(t *testing.T) {
	resetFixture(t)
	page, _ := testBrowser.CurrentPage()

	page.MustEval(`() => {
		window.__testGenSelector = ` + extractSelectorFunction() + `
	}`)

	// test-input has aria-label="Test Input"
	result := page.MustEval(`() => {
		const el = document.querySelector('[aria-label="Test Input"]');
		return window.__testGenSelector(el);
	}`).Str()

	// Should return #test-input (ID takes priority) since test-input has both id and aria-label
	if result != "#test-input" {
		t.Errorf("expected '#test-input' (ID priority), got '%s'", result)
	}

	// Test element that only has aria-label (no ID)
	result = page.MustEval(`() => {
		const el = document.querySelector('[aria-label="Accessible Element"]');
		return window.__testGenSelector(el);
	}`).Str()

	if result != `[aria-label="Accessible Element"]` {
		t.Errorf("expected '[aria-label=\"Accessible Element\"]', got '%s'", result)
	}
}

func TestSelectorByName(t *testing.T) {
	resetFixture(t)
	page, _ := testBrowser.CurrentPage()

	page.MustEval(`() => {
		window.__testGenSelector = ` + extractSelectorFunction() + `
	}`)

	result := page.MustEval(`() => {
		const el = document.querySelector('input[name="password"]');
		return window.__testGenSelector(el);
	}`).Str()

	// Has id="test-password", so ID takes priority
	if result != "#test-password" {
		t.Errorf("expected '#test-password' (ID priority), got '%s'", result)
	}

	// Test select element by name - has id so ID takes priority
	result = page.MustEval(`() => {
		const el = document.querySelector('select[name="country"]');
		return window.__testGenSelector(el);
	}`).Str()

	if result != "#test-select" {
		t.Errorf("expected '#test-select', got '%s'", result)
	}
}

func TestSelectorByPlaceholder(t *testing.T) {
	resetFixture(t)
	page, _ := testBrowser.CurrentPage()

	page.MustEval(`() => {
		window.__testGenSelector = ` + extractSelectorFunction() + `
	}`)

	// Create a temporary input with only placeholder (no id, name, etc.)
	result := page.MustEval(`() => {
		const input = document.createElement('input');
		input.placeholder = 'Unique Placeholder Text';
		document.body.appendChild(input);
		const sel = window.__testGenSelector(input);
		input.remove();
		return sel;
	}`).Str()

	if result != `input[placeholder="Unique Placeholder Text"]` {
		t.Errorf("expected placeholder selector, got '%s'", result)
	}
}

func TestSelectorFallbackNthChild(t *testing.T) {
	resetFixture(t)
	page, _ := testBrowser.CurrentPage()

	page.MustEval(`() => {
		window.__testGenSelector = ` + extractSelectorFunction() + `
	}`)

	// Create an element with no identifying attributes
	result := page.MustEval(`() => {
		const div = document.createElement('div');
		const span = document.createElement('span');
		div.appendChild(span);
		document.body.appendChild(div);
		const sel = window.__testGenSelector(span);
		div.remove();
		return sel;
	}`).Str()

	if !strings.Contains(result, "body >") {
		t.Errorf("expected nth-child fallback path, got '%s'", result)
	}
}

func TestSelectorSkipsAutoGeneratedIDs(t *testing.T) {
	resetFixture(t)
	page, _ := testBrowser.CurrentPage()

	page.MustEval(`() => {
		window.__testGenSelector = ` + extractSelectorFunction() + `
	}`)

	// Create element with auto-generated looking ID
	result := page.MustEval(`() => {
		const div = document.createElement('div');
		div.id = 'react-ab3f7e9d';
		div.setAttribute('data-testid', 'my-component');
		document.body.appendChild(div);
		const sel = window.__testGenSelector(div);
		div.remove();
		return sel;
	}`).Str()

	// Should skip the auto-generated ID and use data-testid
	if result != `[data-testid="my-component"]` {
		t.Errorf("expected data-testid selector (skipping auto-generated ID), got '%s'", result)
	}
}

// --- Event capture tests ---

func TestJSCapturesClick(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", false)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer testBrowser.StopRecording()

	time.Sleep(300 * time.Millisecond)

	page, _ := testBrowser.CurrentPage()
	page.MustElement("#test-button").MustClick()
	time.Sleep(500 * time.Millisecond) // wait for deferred click (300ms dblclick window + buffer)

	events, _ := testBrowser.StopRecording()

	found := false
	for _, evt := range events {
		if evt.Type == "click" && evt.Selector == "#test-button" {
			found = true
			if evt.TagName != "button" {
				t.Errorf("expected tagName 'button', got '%s'", evt.TagName)
			}
			break
		}
	}
	if !found {
		t.Errorf("expected click event with selector '#test-button', got: %+v", events)
	}
}

func TestJSCapturesFill(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", false)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer testBrowser.StopRecording()

	time.Sleep(300 * time.Millisecond)

	page, _ := testBrowser.CurrentPage()
	page.MustElement("#test-input").MustInput("test value")
	time.Sleep(800 * time.Millisecond) // wait for debounce

	events, _ := testBrowser.StopRecording()

	found := false
	for _, evt := range events {
		if evt.Type == "fill" && evt.Value == "test value" {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected fill event with value 'test value', got: %+v", events)
	}
}

func TestJSCapturesKeypress(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", false)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer testBrowser.StopRecording()

	time.Sleep(300 * time.Millisecond)

	page, _ := testBrowser.CurrentPage()
	page.MustElement("#test-input").MustClick()
	if err := page.Keyboard.Press(input.Enter); err != nil {
		t.Fatalf("failed to press Enter: %v", err)
	}
	if err := page.Keyboard.Release(input.Enter); err != nil {
		t.Fatalf("failed to release Enter: %v", err)
	}

	time.Sleep(300 * time.Millisecond)

	events, _ := testBrowser.StopRecording()

	found := false
	for _, evt := range events {
		if evt.Type == "keypress" && evt.Value == "Enter" {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected keypress event with value 'Enter', got: %+v", events)
	}
}

func TestJSSkipsOverlayClicks(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", true)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer testBrowser.StopRecording()

	time.Sleep(300 * time.Millisecond)

	page, _ := testBrowser.CurrentPage()

	// Click on the overlay's minimize button
	page.MustEval(`() => {
		const btn = document.getElementById('__atr-recorder-minimize');
		if (btn) btn.click();
	}`)
	time.Sleep(300 * time.Millisecond)

	events, _ := testBrowser.StopRecording()

	// Should have no click events (overlay clicks are filtered)
	for _, evt := range events {
		if evt.Type == "click" {
			t.Errorf("overlay click should not be recorded, got: %+v", evt)
		}
	}
}

func TestJSMasksPasswordFields(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", false)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer testBrowser.StopRecording()

	time.Sleep(300 * time.Millisecond)

	page, _ := testBrowser.CurrentPage()
	page.MustElement("#test-password").MustInput("secretpass")
	time.Sleep(800 * time.Millisecond) // wait for debounce

	events, _ := testBrowser.StopRecording()

	for _, evt := range events {
		if evt.Type == "fill" && strings.Contains(evt.Selector, "password") {
			if evt.Value != "[password]" {
				t.Errorf("expected password to be masked as '[password]', got '%s'", evt.Value)
			}
			return
		}
	}
	t.Errorf("expected fill event on password field, got: %+v", events)
}

func TestJSDetectsSelectChange(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", false)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer testBrowser.StopRecording()

	time.Sleep(300 * time.Millisecond)

	// Change select value via JS (simulating user interaction)
	page, _ := testBrowser.CurrentPage()
	page.MustEval(`() => {
		const sel = document.getElementById('test-select');
		sel.value = 'uk';
		sel.dispatchEvent(new Event('change', { bubbles: true }));
	}`)
	time.Sleep(300 * time.Millisecond)

	events, _ := testBrowser.StopRecording()

	found := false
	for _, evt := range events {
		if evt.Type == "select_option" && evt.Value == "United Kingdom" {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected select_option event with value 'United Kingdom', got: %+v", events)
	}
}

// --- Shadow DOM tests ---

func TestShadowDOMClickCapture(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", false)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer func() { testBrowser.StopRecording(); testBrowser.ClearRecording() }()

	time.Sleep(300 * time.Millisecond)

	// Click the button inside shadow DOM
	page, _ := testBrowser.CurrentPage()
	page.MustEval(`() => {
		const host = document.getElementById('shadow-host');
		const btn = host.shadowRoot.querySelector('#shadow-btn');
		btn.click();
	}`)
	time.Sleep(500 * time.Millisecond)

	events, _ := testBrowser.StopRecording()

	found := false
	for _, evt := range events {
		if evt.Type == "click" && strings.Contains(evt.Selector, ">>") {
			found = true
			// Should contain the shadow host selector and inner selector
			if !strings.Contains(evt.Selector, "#shadow-host") {
				t.Errorf("expected shadow host '#shadow-host' in selector, got: %s", evt.Selector)
			}
			break
		}
	}
	if !found {
		t.Errorf("expected click event with shadow DOM selector (containing '>>'), got: %+v", events)
	}
}

func TestShadowDOMSelectorGeneration(t *testing.T) {
	resetFixture(t)
	page, _ := testBrowser.CurrentPage()

	// Inject selector generator and test it on shadow DOM elements
	page.MustEval(`() => {
		window.__testGenSelector = ` + extractSelectorFunction() + `
	}`)

	result := page.MustEval(`() => {
		const host = document.getElementById('shadow-host');
		const btn = host.shadowRoot.querySelector('#shadow-btn');
		return window.__testGenSelector(btn);
	}`).Str()

	// Should produce a shadow DOM path: #shadow-host >> [data-testid="shadow-action"]
	if !strings.Contains(result, ">>") {
		t.Errorf("expected shadow DOM selector with '>>', got: %s", result)
	}
	if !strings.Contains(result, "#shadow-host") {
		t.Errorf("expected '#shadow-host' in selector, got: %s", result)
	}
}

// --- Iframe overlay test ---

func TestOverlayOnlyInTopFrame(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", true)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer func() { testBrowser.StopRecording(); testBrowser.ClearRecording() }()

	time.Sleep(500 * time.Millisecond)

	page, _ := testBrowser.CurrentPage()

	// Check overlay exists in top frame
	topHasOverlay := page.MustEval(`() => {
		return !!document.getElementById('__atr-recorder-overlay');
	}`).Bool()
	if !topHasOverlay {
		t.Error("expected overlay in top frame")
	}

	// Check overlay does NOT exist in iframe
	iframeHasOverlay := page.MustEval(`() => {
		const iframe = document.getElementById('test-iframe');
		if (!iframe || !iframe.contentDocument) return false;
		return !!iframe.contentDocument.getElementById('__atr-recorder-overlay');
	}`).Bool()
	if iframeHasOverlay {
		t.Error("overlay should NOT be in iframe, but it was found")
	}

	testBrowser.StopRecording()
}

// --- Click deduplication test ---

func TestClickDeduplication(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", false)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer func() { testBrowser.StopRecording(); testBrowser.ClearRecording() }()

	time.Sleep(300 * time.Millisecond)

	// Rapidly click the same element 5 times within dedup window
	page, _ := testBrowser.CurrentPage()
	for i := 0; i < 5; i++ {
		page.MustEval(`() => { document.getElementById('test-button').click(); }`)
		time.Sleep(50 * time.Millisecond) // within 300ms dedup window
	}
	time.Sleep(500 * time.Millisecond) // wait for deferred click

	events, _ := testBrowser.StopRecording()

	clickCount := 0
	for _, evt := range events {
		if evt.Type == "click" {
			clickCount++
		}
	}
	// Should be 1 or 2 at most (first click goes through, rest deduped)
	if clickCount > 2 {
		t.Errorf("expected at most 2 click events after dedup, got %d from events: %+v", clickCount, events)
	}
}

// --- Double click cancels single click ---

func TestDblclickCancelsPendingClick(t *testing.T) {
	resetFixture(t)

	err := testBrowser.StartRecording("", false)
	if err != nil {
		t.Fatalf("StartRecording failed: %v", err)
	}
	defer func() { testBrowser.StopRecording(); testBrowser.ClearRecording() }()

	time.Sleep(300 * time.Millisecond)

	// Dispatch a dblclick (browser fires click then dblclick)
	page, _ := testBrowser.CurrentPage()
	page.MustEval(`() => {
		const btn = document.getElementById('test-button');
		btn.dispatchEvent(new MouseEvent('click', {bubbles: true, clientX: 100, clientY: 100}));
		btn.dispatchEvent(new MouseEvent('dblclick', {bubbles: true, clientX: 100, clientY: 100}));
	}`)
	time.Sleep(500 * time.Millisecond)

	events, _ := testBrowser.StopRecording()

	hasClick := false
	hasDblClick := false
	for _, evt := range events {
		if evt.Type == "click" {
			hasClick = true
		}
		if evt.Type == "double_click" {
			hasDblClick = true
		}
	}

	if !hasDblClick {
		t.Errorf("expected double_click event, got: %+v", events)
	}
	if hasClick {
		t.Errorf("single click should be cancelled by dblclick, got both in: %+v", events)
	}
}

// extractSelectorFunction returns the generateSelector function from the recorder script
// including shadow DOM support, for use in isolated selector tests.
func extractSelectorFunction() string {
	return `(function() {
  function generateSelector(el) {
    if (!el || el === document.body || el === document.documentElement) return 'body';

    // Shadow DOM: build hostSelector >> innerSelector
    const root = el.getRootNode();
    if (root && root !== document && root.host) {
      const hostSel = generateSelector(root.host);
      const innerSel = generateInnerSelector(el, root);
      return hostSel + ' >> ' + innerSel;
    }

    if (el.id && !/^[a-z]+-[a-f0-9]{4,}$/i.test(el.id) && document.querySelectorAll('#' + CSS.escape(el.id)).length === 1) {
      return '#' + CSS.escape(el.id);
    }

    for (const attr of ['data-testid', 'data-test-id', 'data-cy']) {
      const val = el.getAttribute(attr);
      if (val) return '[' + attr + '="' + val + '"]';
    }

    const ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel) return '[aria-label="' + ariaLabel + '"]';

    const tag = el.tagName.toLowerCase();
    if (['input', 'select', 'textarea'].includes(tag) && el.name) {
      const sel = tag + '[name="' + el.name + '"]';
      if (document.querySelectorAll(sel).length === 1) return sel;
    }

    if (['input', 'textarea'].includes(tag) && el.placeholder) {
      const sel = tag + '[placeholder="' + el.placeholder + '"]';
      if (document.querySelectorAll(sel).length === 1) return sel;
    }

    if (el.classList.length > 0) {
      for (let i = 0; i < el.classList.length; i++) {
        const cls = el.classList[i];
        if (cls.startsWith('__atr-')) continue;
        const sel = tag + '.' + CSS.escape(cls);
        if (document.querySelectorAll(sel).length === 1) return sel;
      }
    }

    const parts = [];
    let current = el;
    while (current && current !== document.body && current !== document.documentElement) {
      const t = current.tagName.toLowerCase();
      const parent = current.parentElement;
      if (!parent) break;
      const siblings = Array.from(parent.children).filter(c => c.tagName.toLowerCase() === t);
      if (siblings.length === 1) {
        parts.unshift(t);
      } else {
        const idx = siblings.indexOf(current) + 1;
        parts.unshift(t + ':nth-child(' + idx + ')');
      }
      current = parent;
    }
    return 'body > ' + parts.join(' > ');
  }
  function generateInnerSelector(el, shadowRoot) {
    if (el.id && !/^[a-z]+-[a-f0-9]{4,}$/i.test(el.id)) return '#' + CSS.escape(el.id);
    for (const attr of ['data-testid', 'data-test-id', 'data-cy']) {
      const val = el.getAttribute(attr);
      if (val) return '[' + attr + '="' + val + '"]';
    }
    const ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel) return '[aria-label="' + ariaLabel + '"]';
    const tag = el.tagName.toLowerCase();
    if (['input', 'select', 'textarea'].includes(tag) && el.name) {
      const sel = tag + '[name="' + el.name + '"]';
      if (shadowRoot.querySelectorAll(sel).length === 1) return sel;
    }
    if (['input', 'textarea'].includes(tag) && el.placeholder) {
      const sel = tag + '[placeholder="' + el.placeholder + '"]';
      if (shadowRoot.querySelectorAll(sel).length === 1) return sel;
    }
    if (el.classList && el.classList.length > 0) {
      for (let i = 0; i < el.classList.length; i++) {
        const cls = el.classList[i];
        const sel = tag + '.' + CSS.escape(cls);
        if (shadowRoot.querySelectorAll(sel).length === 1) return sel;
      }
    }
    const text = el.textContent ? el.textContent.trim() : '';
    if (text && text.length < 50 && ['button', 'a', 'span'].includes(tag)) {
      return tag + ':text("' + text.replace(/"/g, '\\"') + '")';
    }
    const parts = [];
    let current = el;
    while (current && current !== shadowRoot.host) {
      const tg = current.tagName.toLowerCase();
      const parent = current.parentElement;
      if (!parent) break;
      const siblings = Array.from(parent.children).filter(c => c.tagName.toLowerCase() === tg);
      if (siblings.length === 1) parts.unshift(tg);
      else parts.unshift(tg + ':nth-child(' + (siblings.indexOf(current) + 1) + ')');
      current = parent;
    }
    return parts.join(' > ');
  }
  return generateSelector;
  })()`
}
